src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Needs to be merged with https://github.com/hmrc/personal-income-tax-submission-frontend/pull/78
=> Updated element selectors after the twirl update changes

src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature
Updated the header for other dividends amount page, and removed clicking radio buttons for prior data
https://jira.tools.tax.service.gov.uk/browse/SASS-574
=> SASS-574: Updated the header for other dividends amount page, and removed clicking radio buttons

src/test/resources/features/01_dividends.feature
=> SASS-574: Updated tests for no longer having a pre-popped value

src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature, src/test/resources/features/XX_utils.feature
=> [DM] [SASS-601] Fixed continue button step

src/test/resources/features/02_interest.feature
=> SASS-575: Updated taxed/untaxed header name

src/test/resources/features/02_interest.feature
Reverts hmrc/income-tax-submission-journey-tests#53
=> Revert "SASS-575: Updated taxed/untaxed header name"

src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature
Updated the header for uk dividends, and removed clicking radio buttons
https://jira.tools.tax.service.gov.uk/browse/SASS-573
=> SASS-573: Updated the header for uk dividends, and removed clicking radio buttons

src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature
- Updated taxed/untaxed amount titles and removed radio button clicks
- Added test for returning agent to interests
https://jira.tools.tax.service.gov.uk/browse/SASS-576
=> Sass 575: Updated taxed/untaxed amount titles and removed radio button clicks

project/Dependencies.scala, project/build.properties, project/plugins.sbt, src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature, src/test/resources/features/XX_utils.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
- Removing unused code around the prior/other amount radio buttons
- Consolidating the url stepdefs into one
- Updating the wording of the names of a couple features
- Updating dependencies
=> Removing unusued code and merging url stepdefs into one

build.sbt, project/Dependencies.scala, project/plugins.sbt, src/test/resources/cucumber.properties
Updating the dependencies
https://jira.tools.tax.service.gov.uk/browse/SASS-829
=> SASS-829: Updating dependencies

src/test/resources/features/03_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Adding employment flow tests
https://jira.tools.tax.service.gov.uk/browse/SASS-842
=> SASS-842: Added tests for the employment flow

project/Dependencies.scala, src/test/resources/features/03_charities.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-840](https://jira.tools.tax.service.gov.uk/browse/SASS-840)
=> SASS-840 gift aid journey tests

src/test/resources/features/03_charities.feature
=> update agent flow

src/test/resources/features/XX_utils.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/AuthStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
Adding the employment frontend to the utils checks
=> Adding the employment frontend to the utils checks

.bsp/sbt.json, src/test/resources/features/02_interest.feature
Journey test changes for interest design iteration
[SASS-835](https://jira.tools.tax.service.gov.uk/browse/SASS-493)
=> Sass 835 - Interest design iteration journey tests

.bsp/sbt.json, src/test/resources/features/02_interest.feature, src/test/resources/features/XX_utils.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
changing interest url to match what currently in personal FE
=> Sass 835 - Interest Journey test iteration

.bsp/sbt.json, .gitignore, src/test/resources/features/02_interest.feature, src/test/resources/features/XX_utils.feature
Interest cya page heading update
[SASS-493](https://jira.tools.tax.service.gov.uk/browse/SASS-493)
=> SASS-493 interest journey cya heading update

src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> added scenarios for previous interest accounts

src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature, src/test/resources/features/03_charities.feature, src/test/resources/features/99a_dividends_qa_smoke.feature, src/test/resources/features/99b_interest_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Renamed employment and view estimation links
https://jira.tools.tax.service.gov.uk/browse/SASS-1108
=> SASS-1108: Renamed employment and view estimation links

project/plugins.sbt, src/test/resources/features/04_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Added 2 new flows for editing and deleting pre-existing employments
[SASS-1219](https://jira.tools.tax.service.gov.uk/browse/SASS-1219)
=> Added 2 new flows

src/test/resources/features/00_crystallisation.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/AuthStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/AuthLoginPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Addition of Agent and Individual crystallisation journeys
[SASS-1215](https://jira.tools.tax.service.gov.uk/browse/SASS-968)
=> SASS-1215 : Crystallisation journeys

src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/AuthStepDef.scala
=> Get auth submit button via id

src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Changing PAYE Employment to PAYE employment to match prototype
=> changing PAYE employment to match prototype

src/test/resources/features/00_crystallisation.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
SASS-1264 journey test update to include declaration page in crystallisation flows
[SASS-1225](https://jira.tools.tax.service.gov.uk/browse/SASS-1225)
=> SASS-1264 added declaration page to crystallisation journey

src/test/resources/features/03_charities.feature
[SASS-1188](https://jira.tools.tax.service.gov.uk/browse/SASS-1188)
=> [SASS-1188] - Updates maximum flow to include Confirmation page.

src/test/resources/features/03_charities.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Gift aid iteration journey changes
[SASS-1246](https://jira.tools.tax.service.gov.uk/browse/SASS-1246)
=> SASS-1246 - Made iteration changes to gift aid journey

src/test/resources/features/99c_charities_qa_smoke.feature
changed titles in smoke tests to align with journey
[SASS-1246](https://jira.tools.tax.service.gov.uk/browse/SASS-1246)
=> SASS-1246b : changed titles in smoke tests to align with journey

src/test/resources/features/04_employment.feature
Added navigation for travel and entertainment journey tests
https://jira.tools.tax.service.gov.uk/browse/SASS-1533
=> added travel and entertainment journeys

src/test/resources/features/04_employment.feature
- Added tests to check the Navigation for EOY utilities and general service employment benefits section
https://jira.tools.tax.service.gov.uk/browse/SASS-1534
=> Sass 1622: Navigation for EOY utilities and general service employment benefits section

src/test/resources/features/99d_employment_qa_smoke.feature
Create smoke tests that run against QA
[SASS-863-Employment](https://jira.tools.tax.service.gov.uk/browse/SASS-863)
=> SASS-863-Employment Create smoke tests that run against QA

src/test/resources/application.conf, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
Change all `/income-through-software/return/` strings to `/update-and-submit-income-tax-return/`
[SASS-1572](https://jira.tools.tax.service.gov.uk/browse/SASS-1572)
=> SASS-1572: Update acceptance tests page URLs

src/test/resources/features/99d_employment_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
https://jira.tools.tax.service.gov.uk/browse/SASS-1700
=> SASS-1771 Added EOY employment smoke tests

project/Dependencies.scala, project/plugins.sbt, src/test/resources/features/04_employment.feature, src/test/resources/features/99d_employment_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CYAStepDef.scala
- SASS-1658 Added income section tests
https://jira.tools.tax.service.gov.uk/browse/SASS-1658
=> SASS-1658 Added income section tests

src/test/resources/features/04_employment.feature
- Adding reimbursed section tests
https://jira.tools.tax.service.gov.uk/browse/SASS-1725
=> SASS-1725: Adding reimbursed section tests

src/test/resources/features/04_employment.feature
[SASS-1309](https://jira.tools.tax.service.gov.uk/browse/SASS-1309)
=> SASS-1309 - Employment benefits iterations.

src/test/resources/features/04_employment.feature
added tests for assets section in the employment benefits journeys
[SASS-1726](https://jira.tools.tax.service.gov.uk/browse/SASS-1726)
=> SASS-1726 - added tests for assets section of employment benefits

src/test/resources/features/04_employment.feature, src/test/resources/features/99d_employment_qa_smoke.feature
Changed page title in employment journeys.
[SASS-1124](https://jira.tools.tax.service.gov.uk/browse/SASS-1124)
=> SASS-1124 Changed page titles

src/test/resources/features/00_crystallisation.feature
Changed V&C title steps in crystallisation feature
[SASS-1481](https://jira.tools.tax.service.gov.uk/browse/SASS-1481)
=> SASS-1481 : Changed V&C title steps in crystallisation feature

src/test/resources/features/04_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-2050](https://jira.tools.tax.service.gov.uk/browse/SASS-2050)
=> SASS-2050 - Removing an employment iteration.

src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CYAStepDef.scala
Changed some selectors to account for new h2 on cya page
[SASS-2047](https://jira.tools.tax.service.gov.uk/browse/SASS-2047)
=> Updated Journey tests for new h2

src/test/resources/features/04_employment.feature
amended journey tests to change employment to employer
[SASS-2192](https://jira.tools.tax.service.gov.uk/browse/SASS-2192)
=> SASS-2049 Add an employer iteration

src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature, src/test/resources/features/03_charities.feature
=> SASS-2210 commenting out step to be changed 

src/test/resources/features/99d_employment_qa_smoke.feature
=> [SASS-2232] qa full path fix

src/test/resources/features/99d_employment_qa_smoke.feature
Uncommented a relevant smoke test
[SASS-2275](https://jira.tools.tax.service.gov.uk/browse/SASS-2275)
=> SASS-2275, uncommented relevant smoke test

README.md, src/test/resources/features/04_employment.feature, src/test/resources/features/99d_employment_qa_smoke.feature
Updated the text related to the Student Loan Page titles.
Link to JIRA Story
[SASS-2422](https://jira.tools.tax.service.gov.uk/browse/SASS-2422)
=> SASS-2422 Student loans page titles update

src/test/resources/features/05_view_estimation.feature, src/test/resources/features/99e_view_estimation_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Journey Tests for View Estimation
[SASS-2343](https://jira.tools.tax.service.gov.uk/browse/SASS-2211)
=> SASS-2343 view estimation journeys

src/test/resources/features/05_cis.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Added user journey tests for CIS In Year workflow. 
[SASS-2175](https://jira.tools.tax.service.gov.uk/browse/SASS-2175)
=> SASS-2175 - CIS In Year User Journey tests

src/test/resources/features/99d_employment_qa_smoke.feature
updated smoke tests
[SASS-1799](https://jira.tools.tax.service.gov.uk/browse/SASS-1799)
=> SASS-1799 employment details navigation iteration

src/test/resources/features/00_crystallisation.feature
Make the page title in the income tax received page match the h1 heading text.
[SASS-2513](https://jira.tools.tax.service.gov.uk/browse/SASS-2513)
=> SASS-2513: Confirmation Page: Page <title> does not match <h1>

src/test/resources/features/04_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Updating journey tests to link to correct locations after changes made in SASS-2517
Income-tax-submission-frontend
- https://github.com/hmrc/income-tax-submission-frontend/pull/208
Income-tax-employment-frontend
- https://github.com/hmrc/income-tax-employment-frontend/pull/331
[SASS-2517](https://jira.tools.tax.service.gov.uk/browse/SASS-2517)
=> SASS-2517 Updating journey tests for employment journey

src/test/resources/features/00_crystallisation.feature, src/test/resources/features/00_view_estimation.feature, src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature, src/test/resources/features/03_charities.feature, src/test/resources/features/04_employment.feature, src/test/resources/features/05_cis.feature, src/test/resources/features/99a_dividends_qa_smoke.feature, src/test/resources/features/99b_interest_qa_smoke.feature, src/test/resources/features/99c_charities_qa_smoke.feature, src/test/resources/features/99d_employment_qa_smoke.feature, src/test/resources/features/99e_view_estimation_qa_smoke.feature, src/test/resources/features/XX_utils.feature, src/test/scala/uk/gov/hmrc/test/ui/conf/TaxYearHelper.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
Updated Journey tests for new tax year (verified against stub, ideally need to be merged together)
https://github.com/hmrc/income-tax-submission-stub/pull/109
[SASS-2692](https://jira.tools.tax.service.gov.uk/browse/SASS-2663)
=> SASS-2692 : updated for 2023 tax year

src/test/resources/features/06_pensions.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Added pension feature with Payments into Pensions journey tests
[SASS-2097](https://jira.tools.tax.service.gov.uk/browse/SASS-2097)
=> SASS-2097 Payments into pensions journeys

src/test/resources/features/04_employment.feature
Employment expenses iterations journey test changes. Smoke tests will be fixed in another ticket
[SASS-2326](https://jira.tools.tax.service.gov.uk/browse/SASS-2326)
=> Journey test updates for employment expenses iterations

src/test/scala/uk/gov/hmrc/test/ui/conf/TaxYearHelper.scala
=> SASS-2720 - [FIX] Fixes issue with the TaYearHelper.

src/test/resources/features/99a_dividends_qa_smoke.feature, src/test/resources/features/99c_charities_qa_smoke.feature
[SASS-2719](https://jira.tools.tax.service.gov.uk/browse/SASS-2719)
=> SASS-2719 - Changes year to 2023.

src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature, src/test/resources/features/03_charities.feature, src/test/resources/features/04_employment.feature, src/test/resources/features/06_pensions.feature, src/test/resources/features/99d_employment_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonPage.scala
[SASS-2521](https://jira.tools.tax.service.gov.uk/browse/SASS-2521)
=> update for tailoring

src/test/resources/features/04_employment.feature
[SASS-2511](https://jira.tools.tax.service.gov.uk/browse/SASS-2511)
=> SASS-2511 - Employment dates iteration.

src/test/resources/features/05_cis.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-2578](https://jira.tools.tax.service.gov.uk/browse/SASS-2578)
=> SASS-2578 - Uses a third contractor instead of second.

src/test/resources/features/06_pensions.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Sass 2916  add pensions to adding income source page journey test

src/test/resources/features/05_cis.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
SASS-3070 Fix the journey related to adding a new period in CIS when Contractor name is missing
Added scenarios for CIS User journey when contractor name is missing.
[SASS-3070](https://jira.tools.tax.service.gov.uk/browse/SASS-3070)
=> SASS-3070 CIS Journey tests when contractor name is missing

src/test/resources/features/06_pensions.feature
Reverts hmrc/income-tax-submission-journey-tests#162
=> Revert "[SASS-2952] update journey tests for pensions feature new change link"

src/test/resources/features/06_pensions.feature
=> [SASS-2952] updated test for new pensions change link

src/test/resources/features/04_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
=> [SASS-3028] added employment cannot update journey

src/test/resources/features/04_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
Reverts hmrc/income-tax-submission-journey-tests#165
=> Revert "[SASS-3028] added employment cannot update journey"

src/test/resources/features/00_crystallisation.feature, src/test/resources/features/00_view_estimation.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
=> SASS- 3159 - Fixes broken tests related to V&C page titles changes.

README.md, service-manager/start.sh, service-manager/stop.sh
Added two scripts for a more convenient control of service manager.
[SASS-3193](https://jira.tools.tax.service.gov.uk/browse/SASS-3193)
=> [SASS-3193] Added service-manager related scripts.

project/plugins.sbt, src/test/resources/features/99d_employment_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonPage.scala
Updated smoke tests for employment service.
[SASS-3189](https://jira.tools.tax.service.gov.uk/browse/SASS-3189)
=> SASS-3189 Smoke Tests

src/test/resources/features/07_state_benefits.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-3536](https://jira.tools.tax.service.gov.uk/browse/SASS-3536)
=> SASS-3536 - Create Jobseeker's Allowance 'Add missing claim' page.

src/test/resources/features/00_crystallisation.feature, src/test/resources/features/00_view_estimation.feature
Fix journey tests as the V&C page titles have changed in https://github.com/hmrc/income-tax-view-change-frontend/pull/1479
=> Fix journey tests for MISUV-4237 V&C page title change

src/test/resources/features/07_state_benefits.feature
=> revert SASS-3596

src/test/resources/features/07_state_benefits.feature
This reverts commit 6de65262bb65be2a57d0fe195da8662a7493629d.
[SASS-3596](https://jira.tools.tax.service.gov.uk/browse/SASS-3596)
=> Revert "revert SASS-3596"

src/test/resources/features/04_employment.feature, src/test/resources/features/99d_employment_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> added test for student loans changes

src/test/resources/features/00_crystallisation.feature, src/test/resources/features/00_view_estimation.feature
Fix the journey tests as the V&C page titles have changed.
[https://jira.tools.tax.service.gov.uk/browse/SASS-3896](SASS-3896)
=> SASS-3896: Update V&C page title assertions in journey tests

src/test/resources/features/99g_pensions_qa_smoke.feature
Smoke test for pensions journey
[SASS-3855](https://jira.tools.tax.service.gov.uk/browse/SASS-3855)
=> smoke test for pensions for QA

src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature
[SASS-3678](https://jira.tools.tax.service.gov.uk/browse/SASS-3678)
=> SASS-3678 - Create 'Did you have tax taken off?' page.

src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature
[SASS-3679](https://jira.tools.tax.service.gov.uk/browse/SASS-3679)
=> SASS-3679 - Create 'How much tax was taken off?' page.

src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Create 'Review Jobseeker's Allowance claim' Page for Customer Data & HMRC data
[SASS-3681](https://jira.tools.tax.service.gov.uk/browse/SASS-3681)
=> SASS-3681 Create 'Review Jobseeker's Allowance claim' Page for Customer Data & HMRC data

src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Create 'Are you sure you want to remove JSA claim?' page
[SASS-3694](https://jira.tools.tax.service.gov.uk/browse/SASS-3694)
=> SASS-3694 Create 'Are you sure you want to remove JSA claim?' page

src/test/resources/features/00_crystallisation.feature, src/test/resources/features/00_view_estimation.feature, src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature, src/test/resources/features/03_charities.feature, src/test/resources/features/04_employment.feature, src/test/resources/features/05_cis.feature, src/test/resources/features/06_pensions.feature, src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99a_dividends_qa_smoke.feature, src/test/resources/features/99b_interest_qa_smoke.feature, src/test/resources/features/99c_charities_qa_smoke.feature, src/test/resources/features/99d_employment_qa_smoke.feature, src/test/resources/features/99e_view_estimation_qa_smoke.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature, src/test/resources/features/99g_pensions_qa_smoke.feature, src/test/resources/features/XX_utils.feature
[SASS-3946](https://jira.tools.tax.service.gov.uk/browse/SASS-3946)
=> SASS-3946 - Increase the 'Confidence Level' to 250 from 200.

src/test/resources/features/04_employment.feature
[Add a link to the relevant story in Jira](https://jira.tools.tax.service.gov.uk/browse/SASS-3946)
SASS-3946 Increase the 'Confidence Level' to 250 from 200
=> SASS-3946 Increase the 'Confidence Level' to 250 from 200

src/test/resources/features/07_state_benefits.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-3905](https://jira.tools.tax.service.gov.uk/browse/SASS-3905)
=> SASS-3905 - JSA Implement 'view' link functionality.

src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Create 'Review Jobseeker's Allowance claim' Page for removed HMRC claim
[SASS-3714](https://jira.tools.tax.service.gov.uk/browse/SASS-3714)
=> SASS-3714 Create 'Review Jobseeker's Allowance claim' Page for removed HMRC claim

src/test/resources/features/99a_dividends_qa_smoke.feature, src/test/resources/features/99b_interest_qa_smoke.feature, src/test/resources/features/99c_charities_qa_smoke.feature
=> fixed test data on QA and unignored tests

src/test/resources/features/99h_cis_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Smoke tests for CIS service
[SASS-4074](https://jira.tools.tax.service.gov.uk/browse/SASS-4074)
=> SASS-4074 Smoke tests for CIS

project/build.properties, project/plugins.sbt, src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-3715](https://jira.tools.tax.service.gov.uk/browse/SASS-3715)
=> SASS-3715 - JSA 'Restore claim' functionality & navigation.

src/test/resources/features/07_state_benefits.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-3786](https://jira.tools.tax.service.gov.uk/browse/SASS-3786)
=> SASS-3786 - In-year: Create 'Review JSA claim' page.

src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature
Create 'have you completed this section?' page
[SASS-3955](https://jira.tools.tax.service.gov.uk/browse/SASS-3955)
=> SASS-3955 - Create 'have you completed this section?' page

project/Dependencies.scala, src/test/resources/features/07_state_benefits.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Enable Back button on State Benefits FE
[SASS-4099](https://jira.tools.tax.service.gov.uk/browse/SASS-4099)
=> SASS-4099 - Enable Back button on State Benefits FE

src/test/resources/features/07_state_benefits.feature
Fix Edit Start Date
[SASS-4014](https://jira.tools.tax.service.gov.uk/browse/SASS-4014)
=> SASS-4014 - Fix Edit Start Date

src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature
[SASS-4085](https://jira.tools.tax.service.gov.uk/browse/SASS-4085)
=> SASS-4085 - Development of ESA.

project/build.properties, src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/Runner.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Add Journey and Smoke tests for ESA
[SASS-4109](https://jira.tools.tax.service.gov.uk/browse/SASS-4109)
=> SASS-4109 - Add Journey and Smoke tests for ESA

project/Dependencies.scala, src/test/resources/application.conf, src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/conf/TaxYearHelper.scala, src/test/scala/uk/gov/hmrc/test/ui/conf/TestConfiguration.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/Runner.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/SmokeRunner.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/ZapRunner.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/AuthStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CYAStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/driver/BrowserDriver.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/AuthLoginPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PersonalIncomePage.scala
Remove 'Have you completed this section' page
[SASS-4106](https://jira.tools.tax.service.gov.uk/browse/SASS-4106)
=> SASS-4106 - Remove 'Have you completed this section' page

src/test/resources/features/06_pensions.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/Runner.scala
=> Ignoring Pensions journey tests temporarily.

src/test/resources/features/06_pensions.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/Runner.scala
Re-enable Pensions Journey tests
=> SASS-4316: Bug Fix to SASS-4183

src/test/resources/features/08_additional_information.feature, src/test/resources/features/99b_interest_qa_smoke.feature, src/test/resources/features/99i_additional_information_qa_smoke.feature
=> SASS-4424 Smoke test for additional info

src/test/resources/features/07_state_benefits.feature
SASS-4384 Validation on the 'How much JSA did you get?'
[SASS-4384](https://jira.tools.tax.service.gov.uk/browse/SASS-4384)
=> SASS-4384 Validation on the 'How much JSA did you get?'

project/Dependencies.scala, src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature
[SASS-4459](https://jira.tools.tax.service.gov.uk/browse/SASS-4459)
=> SASS-4459 update content for the end date question page

src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature
[SASS-4460](https://jira.tools.tax.service.gov.uk/browse/SASS-4460)
=> SASS-4460 - Change JSA/ESA page order

src/test/resources/features/07_state_benefits.feature
Added a new scenario to check the correct flow of questionnaire.
[SASS-4461](https://jira.tools.tax.service.gov.uk/browse/SASS-4461)
=> SASS-4461 P60/P45 content changes to JSA/ESA

src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
[SASS-4471](https://jira.tools.tax.service.gov.uk/browse/SASS-4471)
=> SASS-4471 - All dates must be on one line.

src/test/scala/uk/gov/hmrc/test/ui/driver/BrowserDriver.scala
=> [FIX] Resolves issue with chrome 111.

src/test/resources/features/06_pensions.feature, src/test/resources/features/99g_pensions_qa_smoke.feature
=> SASS-3604 enable pensions journey test

src/test/resources/features/04_employment.feature, src/test/resources/features/99d_employment_qa_smoke.feature
[SASS-4487](https://jira.tools.tax.service.gov.uk/browse/SASS-4487)
=> SASS-4487 update content for 'What is the PAYE ref?' page

src/test/resources/features/04_employment.feature
[SASS-4483](https://jira.tools.tax.service.gov.uk/browse/SASS-4483)
=> SASS-4483 - 'When did you start working at...' page

src/test/resources/features/04_employment.feature, src/test/resources/features/99d_employment_qa_smoke.feature
[SASS-4488](https://jira.tools.tax.service.gov.uk/browse/SASS-4488)
=> SASS-4488 - 'What is the Payroll ID?' page.

src/test/resources/features/06_pensions.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/Runner.scala
=> SASS-4618 ignore failing pensions test

src/test/resources/features/00_crystallisation.feature, src/test/resources/features/00_view_estimation.feature, src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature, src/test/resources/features/03_charities.feature, src/test/resources/features/04_employment.feature, src/test/resources/features/05_cis.feature, src/test/resources/features/06_pensions.feature, src/test/resources/features/07_state_benefits.feature, src/test/resources/features/08_additional_information.feature, src/test/resources/features/99a_dividends_qa_smoke.feature, src/test/resources/features/99b_interest_qa_smoke.feature, src/test/resources/features/99c_charities_qa_smoke.feature, src/test/resources/features/99d_employment_qa_smoke.feature, src/test/resources/features/99e_view_estimation_qa_smoke.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature, src/test/resources/features/99g_pensions_qa_smoke.feature, src/test/resources/features/99h_cis_qa_smoke.feature, src/test/resources/features/99i_additional_information_qa_smoke.feature, src/test/resources/features/XX_utils.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Change tax year and ignore some tests

src/test/resources/features/04_employment.feature, src/test/resources/features/99d_employment_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/Runner.scala
[SASS-4484](https://jira.tools.tax.service.gov.uk/browse/SASS-4484)
=> SASS 4484 - 'Did you leave employer between' page

src/test/resources/features/08_additional_information.feature
=> fix interest failing tests

src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/Runner.scala
=> change tag to MVP

src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/Runner.scala
=> SASS-4536-add-ignore-tag

src/test/resources/features/99a_dividends_qa_smoke.feature, src/test/resources/features/99c_charities_qa_smoke.feature, src/test/resources/features/99d_employment_qa_smoke.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature, src/test/resources/features/99g_pensions_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Clean smoke tests

README.md, project/Dependencies.scala, run_tests_screenshots.sh, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/ScreenshotRunner.scala, src/test/scala/uk/gov/hmrc/test/ui/driver/BrowserDriver.scala
=> screenshot journeys

src/test/resources/features/06_pensions.feature
=> SASS-2053 ignore pensions test

src/test/resources/features/06_pensions.feature
=> SASS-4958 fix pensions journey test

src/test/resources/features/00_crystallisation.feature
=> SASS-4960 ignore crystallisation test

src/test/resources/features/05_cis.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonPage.scala
=> SASS-4966 Test CIS fields retain values on Back

src/test/resources/features/99h_cis_qa_smoke.feature
[FIX CIS QA TEST](ADD URL HERE)
=> Fix CIS QA tests

run_tests.sh, src/test/resources/features/05_cis.feature, src/test/resources/features/07_state_benefits.feature, src/test/resources/features/XX_utils.feature
=> Stop using autofill

src/test/resources/features/06_pensions.feature
=> ignore Pension tests

src/test/resources/features/06_pensions.feature
=> SASS-5151 enable pensions journey test

src/test/resources/features/06_pensions.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-3317 income from overseas pensions

src/test/resources/features/06_pensions.feature
=> SASS-5272 update pensions journey test

src/test/resources/features/06_pensions.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-5314 overseas transfer charges

src/test/resources/features/06_pensions.feature
=> SASS-5349 ignore failing pensions test

src/test/resources/features/06_pensions.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-5019 pension lifetime allowance

src/test/resources/features/06_pensions.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-3315 annual allowance

src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
=> SASS-5412 fix journey test failure

src/test/resources/features/05_cis.feature, src/test/resources/features/99h_cis_qa_smoke.feature
[SASS-5387](https://jira.tools.tax.service.gov.uk/browse/SASS-5316)
=> CIS scenario update -SASS-5387

src/test/resources/features/06_pensions.feature, src/test/resources/features/09_about_you.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> add journey test for About you

src/test/resources/features/04_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[Sass 5072](https://jira.tools.tax.service.gov.uk/browse/SASS-5072)
=> Sass 5072 lumpsum test

src/test/resources/features/04_employment.feature
=> Update lumpsum test scenario update -SASS-5072

src/test/resources/features/10_property.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-5243](https://jira.tools.tax.service.gov.uk/browse/SASS-5243)
=> UK Property feature -SASS-5243

src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-5342 Fix the failures

src/test/resources/features/07_state_benefits.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-5819](https://jira.tools.tax.service.gov.uk/browse/SASS-5189)
=> sb error msg specific fix-SASS-5819

src/test/resources/features/10_about_your_work.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonPage.scala
=> About your work tests

src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[Fix property bug](ADD URL HERE)
=> Fix property bug

src/test/resources/features/10_property.feature
[fix property test](ADD URL HERE)
=> fix property test

src/test/resources/features/11_property.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-5418](https://jira.tools.tax.service.gov.uk/browse/SASS-5418)
=> Property SASS-5418

src/test/resources/features/11_property.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-5420 Claim Income allowance &CYA

project/plugins.sbt, run_tests.sh, src/test/resources/features/09_about_you.feature, src/test/resources/features/10_about_your_work.feature, src/test/resources/features/12_property_pensions_investments.feature, src/test/resources/features/13_capital_gains.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/TailoringRunner.scala
[SASS-5717](https://jira.tools.tax.service.gov.uk/browse/SASS-5717)
=> Ignore TYR II tests and add new Tailoring runner tag

project/plugins.sbt, run_tests.sh
=> revert changes in run_test.sh file

src/test/resources/features/11_property.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-5706](https://jira.tools.tax.service.gov.uk/browse/SASS-5706)
=> SASS-5076 Property- Income journey test 1

project/Dependencies.scala, src/test/resources/features/06_pensions.feature
=> ignore pensions tests whilst investigating failure

src/test/resources/features/02_interest.feature, src/test/resources/features/03_charities.feature
=> ignore failed tests whilst investigating

src/test/resources/features/04_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Property- Adjustments link

src/test/resources/features/11_property.feature
=> ignore test whilst Team B fix

src/test/resources/features/11_property.feature
[SASS-5496](https://jira.tools.tax.service.gov.uk/browse/SASS-5946)
=> Property- SASS-5496 fix #2

src/test/resources/features/11_property.feature
=> Property- ignore fix #3

src/test/resources/features/11_property.feature
=> Property- fix property link error fix #4

run_tailoring_tests.sh, src/test/resources/features/09_about_you.feature, src/test/resources/features/99j_about-you_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/TailoringBetaRunner.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-5715 Journey test for about you

src/test/resources/features/11_property.feature, src/test/resources/features/99k_property_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-6088](https://jira.tools.tax.service.gov.uk/browse/SASS-6088)
=> SASS-6088 Adjustments journey test

project/plugins.sbt, src/test/resources/features/02_interest.feature, src/test/resources/features/03_charities.feature
=> remove ignore tag

src/test/resources/features/08_additional_information.feature, src/test/resources/features/11_property.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/ZapRunner.scala
=> edit Zap runner

src/test/resources/features/11_property.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-5805](https://jira.tools.tax.service.gov.uk/browse/SASS-5805)
=> Property- SASS-5805

src/test/resources/features/11_property.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
[SASS-5837](https://jira.tools.tax.service.gov.uk/browse/SASS-5837)
=> SASS-5837-Non PIA Expenses

src/test/resources/features/14_self_Employement.feature
=> ignore agent content for self employment

build.sbt, src/test/resources/features/09_about_you.feature, src/test/resources/features/12_property_pensions_investments.feature, src/test/resources/features/99l_property_pensions_investment_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-6403 payment into pensions journey test

src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
=> fix failing journey test

run_self_employment_tests.sh, src/test/resources/features/14_self_Employement.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/SelfEmploymentRunner.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-6517 add seperate runner for self employment journey

src/test/resources/features/14_self_Employement.feature
=> SASS-6560 remove general tag

run_self_employment_tests.sh
=> SASS-6566 update self-employment shell script

src/test/resources/features/14_self_Employement.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Sass 6559 - Self employment income journey

src/test/resources/features/04_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> employment OPW

src/test/resources/features/tailor_your_return_II/02_property_pensions_investments.feature
=> fix failing tests

src/test/resources/features/11_property.feature
=> Property- Update TaxYear for stub tests NINOs #1

src/test/resources/features/tailor_your_return_II/00_about_you.feature, src/test/resources/features/tailor_your_return_II/01_work_and_taxable_state_benefits.feature, src/test/resources/features/tailor_your_return_II/02_property_pensions_investments.feature, src/test/resources/features/tailor_your_return_II/03_payment_into_pensions.feature, src/test/resources/features/tailor_your_return_II/04_add-sections.feature
=> Fix and refactor tailoring test

run_self_employment_tests.sh, src/test/resources/features/14_self_Employement.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Sass 6818 - save and continue on each expenses task list section

src/test/resources/features/06_pensions.feature
=> SASS-6952 enable pensions test

project/plugins.sbt, src/test/resources/features/08_additional_information.feature, src/test/resources/features/99i_additional_information_qa_smoke.feature
=> update gains test

src/test/resources/features/08_additional_information.feature
=> SASS-7199 ignore test until they have been fixed

src/test/resources/features/06_pensions.feature
=> SASS-7306 add new test for prior data income from pension

src/test/resources/features/06_pensions.feature
=> SASS-7320 ignore failing test

src/test/resources/features/08_additional_information.feature
=> remove ignore tag for Additional info

src/test/resources/features/99i_additional_information_qa_smoke.feature
=> update gains smoke test

src/test/resources/features/14_self_Employement.feature
=> SASS-7547 update goods to sell

src/test/resources/features/14_self_Employement.feature
=> SASS-7555 fix journey test

src/test/resources/features/06_pensions.feature
=> SASS-7558 update country for short service refund

src/test/resources/features/14_self_Employement.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-7430 work place running cost

src/test/resources/features/06_pensions.feature
=> SASS-7594 update income from pensions state pensions

accessibility-assessment.json, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/BaseStepDef.scala
=> Add exclusion for auth login accessibility

accessibility-assessment.json
=> exclude accessibility test until error type fix is created

accessibility-assessment.json, run_employment_tests.sh, src/test/resources/features/04_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/EmploymentRunner.scala
=> revert excluded endpoints

src/test/resources/features/14_self_Employement.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-7906 fix for journey test failures

src/test/resources/features/14_self_Employement.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-7946 zero emission cars

project/plugins.sbt, src/test/resources/features/04_employment.feature, src/test/resources/features/05_cis.feature, src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99h_cis_qa_smoke.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Fix for state benefits and cis failing tests

src/test/resources/features/03_charities.feature, src/test/resources/features/08_additional_information.feature, src/test/resources/features/11_property.feature
=> ignore failing tests until SASS-7953 is complete

src/test/resources/features/07_state_benefits.feature
=> State Benefits Tests

src/test/resources/features/07_state_benefits.feature
=> Fix state benefits TY test failures

src/test/resources/features/04_employment.feature
=> Fix employmentTest

src/test/resources/features/tailor_your_return_II/01_work_and_taxable_state_benefits.feature, src/test/resources/features/tailor_your_return_II/02_property_pensions_investments.feature, src/test/resources/features/tailor_your_return_II/04_add-sections.feature
=> update tyr tests

src/test/resources/features/04_employment.feature
=> Employment test ignored

src/test/resources/features/04_employment.feature, src/test/resources/features/05_cis.feature
=> CIS Test fix - Update SASS-7953 rebased

src/test/resources/features/02_interest.feature, src/test/resources/features/03_charities.feature, src/test/resources/features/08_additional_information.feature
=> fix interest tests

src/test/resources/features/pensions/02A_uk_pension_income.feature, src/test/resources/features/pensions/03_pension_annual_allowance.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-8362 fix failing test

src/test/resources/features/11_property.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Fix property test failure

src/test/resources/features/11_property.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Fix Property test failure #2

src/test/resources/features/03_charities.feature, src/test/resources/features/08_additional_information.feature
=> Amend test failures

project/Dependencies.scala, project/build.properties, project/plugins.sbt, run_employment_tests.sh, run_pensions_tests.sh, run_self_employment_tests.sh, run_smoke_tests_qa.sh, run_tailoring_tests.sh, run_tests.sh, run_tests_screenshots.sh, run_zap_tests.sh, run_zap_tests_local.sh, src/test/scala/uk/gov/hmrc/test/ui/driver/BrowserDriver.scala
=> SASS-8375: Update ui-test-runner

src/test/resources/features/pensions/05A_payments_into_overseas_pensions.feature
=> SASS-8412 5c journey test

src/test/resources/features/11_property.feature
=> UK property- ignore steps 

src/test/resources/features/04_employment.feature
=> Employment Journey Tests fix

src/test/resources/features/11_property.feature
=> Property addSections tests fix

src/test/resources/features/tailor_your_return_II/00_about_you.feature, src/test/resources/features/tailor_your_return_II/01_work_and_taxable_state_benefits.feature, src/test/resources/features/tailor_your_return_II/02_property_pensions_investments.feature, src/test/resources/features/tailor_your_return_II/03_payment_into_pensions.feature, src/test/resources/features/tailor_your_return_II/04_add-sections.feature
=> Change start page title in test

src/test/resources/features/pensions/05C_overseas_transfer_charges.feature
=> SASS-8610 update overseas transfer charges

src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Duplicate string name was causing failing tests.
=> SASS-8616: Adjust a duplicate string

src/test/resources/features/11_property.feature
=> WIP property & make changes to tests fix

src/test/resources/features/tailor_your_return_II/04_add-sections.feature, src/test/resources/features/tailor_your_return_II/05_charitable_donations.feature, src/test/resources/features/tailor_your_return_II/06_employment.feature, src/test/resources/features/tailor_your_return_II/07_self_employment.feature, src/test/resources/features/tailor_your_return_II/08_employment_support_allowance.feature, src/test/resources/features/tailor_your_return_II/09_job_seekers_allowance.feature, src/test/resources/features/tailor_your_return_II/10_pensions.feature, src/test/resources/features/tailor_your_return_II/11_payment_into_pensions.feature, src/test/resources/features/tailor_your_return_II/12_uk_interest.feature, src/test/resources/features/tailor_your_return_II/13_uk_dividends_shares_loans.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Add test only endpoint to enhance test performance

src/test/resources/features/pensions/01_payments_into_pensions.feature
=> SASS-8738 payment into pensions test

src/test/resources/features/tailor_your_return_II/01_work_and_taxable_state_benefits.feature, src/test/resources/features/tailor_your_return_II/02_property_pensions_investments.feature, src/test/resources/features/tailor_your_return_II/03_payment_into_pensions.feature, src/test/resources/features/tailor_your_return_II/04_add-sections.feature, src/test/resources/features/tailor_your_return_II/05_charitable_donations.feature, src/test/resources/features/tailor_your_return_II/06_employment.feature, src/test/resources/features/tailor_your_return_II/07_self_employment.feature, src/test/resources/features/tailor_your_return_II/08_employment_support_allowance.feature, src/test/resources/features/tailor_your_return_II/09_job_seekers_allowance.feature, src/test/resources/features/tailor_your_return_II/10_pensions.feature, src/test/resources/features/tailor_your_return_II/11_payment_into_pensions.feature, src/test/resources/features/tailor_your_return_II/12_uk_interest.feature, src/test/resources/features/tailor_your_return_II/13_uk_dividends_shares_loans.feature
=> Ignore test until SASS-8671 is merged

src/test/resources/features/tailor_your_return_II/01_work_and_taxable_state_benefits.feature, src/test/resources/features/tailor_your_return_II/02_property_pensions_investments.feature, src/test/resources/features/tailor_your_return_II/03_payment_into_pensions.feature, src/test/resources/features/tailor_your_return_II/04_add-sections.feature, src/test/resources/features/tailor_your_return_II/05_charitable_donations.feature, src/test/resources/features/tailor_your_return_II/06_employment.feature, src/test/resources/features/tailor_your_return_II/07_self_employment.feature, src/test/resources/features/tailor_your_return_II/08_employment_support_allowance.feature, src/test/resources/features/tailor_your_return_II/09_job_seekers_allowance.feature, src/test/resources/features/tailor_your_return_II/10_pensions.feature, src/test/resources/features/tailor_your_return_II/11_payment_into_pensions.feature, src/test/resources/features/tailor_your_return_II/12_uk_interest.feature, src/test/resources/features/tailor_your_return_II/13_uk_dividends_shares_loans.feature
=> remove ignore tags

src/test/resources/features/pensions/02A_uk_pension_income.feature
=> SASS-8783 uk pension income

src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> update charities elements

src/test/resources/features/pensions/02B_state_pension.feature
=> SASS-8876 state pensions

src/test/resources/features/05_cis.feature, src/test/resources/features/07_state_benefits.feature
=> WIP state_benefits-fix test

accessibility-assessment.json, src/test/resources/features/selfEmployment/SelfEmployment_InYear.feature
=> SASS-8978 accesibilty issues

src/test/resources/features/selfEmployment/SelfEmploymentAccuralDeclareExpensesJourney.feature, src/test/resources/features/selfEmployment/SelfEmploymentAccuralUseMaximumTradingAllowanceJourney.feature, src/test/resources/features/selfEmployment/SelfEmploymentCashAccountJourney.feature
=> SASS-9473 update feature file name

src/test/resources/features/tailor_your_return_II/05_charitable_donations.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Task List Donations using Gif Aid hyperlink

src/test/resources/features/tailor_your_return_II/13_uk_dividends_shares_loans.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> stock dividends mini journey

src/test/resources/features/tailor_your_return_II/13_uk_dividends_shares_loans.feature
=> fix test failure

src/test/resources/features/tailor_your_return_II/13_uk_dividends_shares_loans.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> add journey test for TYR stock dividends mini journey

src/test/resources/features/tailor_your_return_II/13_uk_dividends_shares_loans.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Add test for free and redeemable shares mini journey

src/test/resources/features/tailor_your_return_II/13_uk_dividends_shares_loans.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Add tests for dividends from unit trust and investments

src/test/resources/features/tailor_your_return_II/13_uk_dividends_shares_loans.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-9675 Add test for company loans written off

src/test/resources/features/tailor_your_return_II/14_uk_insurance_gains.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-9957 - add tests for Uk Gains mini journeys

src/test/resources/features/tailor_your_return_II/12_uk_interest.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-10010 add tests for interest savings mini journey

src/test/resources/features/tailor_your_return_II/06_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> test for employment mini journey

src/test/resources/features/11_property.feature
=> Property ESBA test step failure

src/test/resources/features/tailor_your_return_II/07_self_employment.feature
=> CIS Hyperlink for CTL

src/test/resources/features/tailor_your_return_II/08_employment_support_allowance.feature, src/test/resources/features/tailor_your_return_II/09_job_seekers_allowance.feature
=> ESA & JSA CTL journey

run_property_tests.sh, src/test/resources/features/property_rar_combined/00_property.feature, src/test/resources/features/property_rar_combined/01_rent-a-room.feature, src/test/resources/features/property_rar_combined/02_rentals_rar.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/PropertyRunner.scala
=> Add property runner

src/test/resources/features/property_rar_combined/00_property.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> property rental income fix #1

src/test/resources/features/property_rar_combined/00_property.feature, src/test/resources/features/property_rar_combined/01_rent-a-room.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Property test and esba header fix

src/test/resources/features/selfEmployment/SelfEmploymentAccuralDeclareExpensesJourney.feature, src/test/resources/features/selfEmployment/SelfEmploymentAccuralUseMaximumTradingAllowanceJourney.feature
=> SASS-12070 remove electric

README.md, src/test/resources/features/tailor_your_return_II/05_charitable_donations.feature
=> charities have you completed section navigation SASS-10293

src/test/resources/features/property_rar_combined/00_property.feature, src/test/resources/features/property_rar_combined/01_rent-a-room.feature, src/test/resources/features/property_rar_combined/02_rentals_rar.feature
=> WIP property test

project/Dependencies.scala
upgrade ui test runner
[SASS-10253](https://jira.tools.tax.service.gov.uk/browse/SASS-10253)
=> SASS-10253

project/Dependencies.scala
=> Upgraded ui-test-runner to fix browser issue

src/test/resources/features/04_employment.feature, src/test/resources/features/tailor_your_return_II/06_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala
=> Sass 10253

project/Dependencies.scala, src/test/resources/features/04_employment.feature, src/test/resources/features/tailor_your_return_II/06_employment.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala
=> upgrade ui test runner and revert changes

src/test/resources/features/tailor_your_return_II/05_charitable_donations.feature
add have you finished this section
[SASS-10254](https://jira.tools.tax.service.gov.uk/browse/SASS-10254)
=> SASS-10254

src/test/resources/features/tailor_your_return_II/05_charitable_donations.feature, src/test/resources/features/tailor_your_return_II/08_employment_support_allowance.feature, src/test/resources/features/tailor_your_return_II/09_job_seekers_allowance.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
add have you finished this section page
[SASS-10369](https://jira.tools.tax.service.gov.uk/browse/SASS-10369)
=> SASS-10369

README.md, src/test/resources/features/selfEmployment/SelfEmploymentAccuralDeclareExpensesJourney.feature
=> [SASS-10384]Self-Employment - Irrecoverable Debts Bug

src/test/resources/features/tailor_your_return_II/13_uk_dividends_shares_loans.feature
add section completed page to dividends
[SASS-10402](https://jira.tools.tax.service.gov.uk/browse/SASS-10402)
=> SASS-10402

README.md, run_tests_screenshots.sh, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/util/ScreenshotUtil.scala, src/test/scala/uk/gov/hmrc/test/ui/util/TimeMachine.scala
- Added facility to take automatic screenshots of a chosen journey.
- Copied specs for self-employment with the intent of them being updated to trigger all error messages for Welsh translation QA
=> SASS-10341: Fix automatic screenshot facility

src/test/resources/features/tailor_your_return_II/12_uk_interest.feature
add have you completed this section to Interest
[SASS-10406](https://jira.tools.tax.service.gov.uk/browse/SASS-10406)
=> SASS-10406

src/test/resources/features/selfEmployment/SelfEmploymentAccrualAccountingJourney.feature, src/test/resources/features/selfEmployment/SelfEmploymentAccuralDeclareExpensesJourney.feature, src/test/resources/features/selfEmployment/SelfEmploymentAccuralUseMaximumTradingAllowanceJourney.feature, src/test/resources/features/selfEmployment/SelfEmploymentCashAccountJourney.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/AuthStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonPage.scala
=> Sass jt fixes

src/test/resources/features/08_additional_information.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
add secondary agent for Gains
[SASS-10485](https://jira.tools.tax.service.gov.uk/browse/SASS-10485)
=> SASS-10485

src/test/resources/features/property_rar_combined/03_uk_and_foreign_property.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Added UK and Foreign property feature and initial journey

src/test/resources/features/tailor_your_return_II/06_employment.feature
add section completed test to employment 
[SASS-10521](https://jira.tools.tax.service.gov.uk/browse/SASS-10521)
=> SASS-10521

src/test/resources/features/property_rar_combined/03_uk_and_foreign_property.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Added UK and foreign property steps

src/test/resources/features/property_rar_combined/03_uk_and_foreign_property.feature
=> SASS-9059: Add  'How much total income did you get from all of your UK and foreign properties?' page to the journey

src/test/resources/features/property_rar_combined/03_uk_and_foreign_property.feature
=> SASS-9059: Amend agent heading for TotalIncome

src/test/resources/features/05_cis.feature
=> SASS-10687

src/test/resources/features/05_cis.feature, src/test/resources/features/property_rar_combined/03_uk_and_foreign_property.feature, src/test/resources/features/tailor_your_return_II/01_work_and_taxable_state_benefits.feature, src/test/resources/features/tailor_your_return_II/02_property_pensions_investments.feature, src/test/resources/features/tailor_your_return_II/07_self_employment.feature, src/test/resources/features/tailor_your_return_II/14_uk_insurance_gains.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-10687 add completed section to CIS

src/test/resources/features/selfEmployment/SelfEmploymentAccuralUseMaximumTradingAllowanceJourney.feature
add ema test to self-employmentt
[SASS-10358](https://jira.tools.tax.service.gov.uk/browse/SASS-10358)
=> SASS-10589 - add ema test to self-employmentt

src/test/resources/features/tailor_your_return_II/00_about_you.feature
=> SASS-10720 - fix test

src/test/resources/features/pensions/05A_payments_into_overseas_pensions.feature, src/test/resources/features/pensions/05B_income_from_overseas_pensions.feature, src/test/resources/features/pensions/05C_overseas_transfer_charges.feature, src/test/resources/features/pensions/05D_short_service_refunds.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> fix pensions tests

src/test/resources/features/08_additional_information.feature, src/test/resources/features/tailor_your_return_II/13_uk_dividends_shares_loans.feature
=> SASS-10732 - add ema tests to dividends

src/test/resources/features/07_state_benefits.feature, src/test/resources/features/tailor_your_return_II/08_employment_support_allowance.feature, src/test/resources/features/tailor_your_return_II/09_job_seekers_allowance.feature
=> SASS-10703 - add ema tests to state benefits

src/test/resources/features/07_state_benefits.feature
=> SASS-10703 - comment out test

src/test/resources/features/tailor_your_return_II/08_employment_support_allowance.feature, src/test/resources/features/tailor_your_return_II/09_job_seekers_allowance.feature
=> comment out steps

src/test/resources/features/property_rar_combined/03_uk_and_foreign_property.feature
=> Added 'Non-UK resident landlord' page steps

src/test/resources/features/property_rar_combined/03_uk_and_foreign_property.feature
=> SASS-10745: Amend agent message

src/test/resources/features/00_crystallisation.feature, src/test/resources/features/00_view_estimation.feature, src/test/resources/features/01_dividends.feature, src/test/resources/features/02_interest.feature, src/test/resources/features/03_charities.feature, src/test/resources/features/04_employment.feature, src/test/resources/features/05_cis.feature, src/test/resources/features/07_state_benefits.feature, src/test/resources/features/08_additional_information.feature, src/test/resources/features/13_capital_gains.feature, src/test/resources/features/pensions/01_payments_into_pensions.feature, src/test/resources/features/pensions/02A_uk_pension_income.feature, src/test/resources/features/pensions/02B_state_pension.feature, src/test/resources/features/pensions/03_pension_annual_allowance.feature, src/test/resources/features/pensions/04_unauthorised_payments_from_pensions.feature, src/test/resources/features/pensions/05A_payments_into_overseas_pensions.feature, src/test/resources/features/pensions/05B_income_from_overseas_pensions.feature, src/test/resources/features/pensions/05C_overseas_transfer_charges.feature, src/test/resources/features/pensions/05D_short_service_refunds.feature, src/test/resources/features/property_rar_combined/00_property.feature, src/test/resources/features/property_rar_combined/01_rent-a-room.feature, src/test/resources/features/property_rar_combined/02_rentals_rar.feature, src/test/resources/features/property_rar_combined/03_uk_and_foreign_property.feature, src/test/resources/features/property_rar_combined/04_foreign_property.feature, src/test/resources/features/selfEmployment/SelfEmploymentAccrualAccountingJourney.feature, src/test/resources/features/selfEmployment/SelfEmploymentAccuralUseMaximumTradingAllowanceJourney.feature, src/test/resources/features/selfEmployment/SelfEmploymentCashAccountJourney.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
=> fix income tax return title

src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
=> SASS-10496: Update service name

src/test/resources/features/selfEmployment/SelfEmploymentAccrualAccountingJourney.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
=> SASS-quickFix amend capitalisation

src/test/resources/features/selfEmployment/SelfEmploymentAccrualAccountingJourney.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Amend correct heading ad hyperlinks for Annual investment allowance and Structures and buildings allowance

src/test/resources/features/07_state_benefits.feature, src/test/resources/features/99a_dividends_qa_smoke.feature, src/test/resources/features/99b_interest_qa_smoke.feature, src/test/resources/features/99c_charities_qa_smoke.feature, src/test/resources/features/99d_employment_qa_smoke.feature, src/test/resources/features/99e_view_estimation_qa_smoke.feature, src/test/resources/features/99f_state_benefits_qa_smoke.feature, src/test/resources/features/99g_pensions_qa_smoke.feature, src/test/resources/features/99h_cis_qa_smoke.feature, src/test/resources/features/99i_additional_information_qa_smoke.feature, src/test/resources/features/99j_about-you_qa_smoke.feature, src/test/resources/features/99k_property_qa_smoke.feature, src/test/resources/features/99l_property_pensions_investment_qa_smoke.feature, src/test/resources/features/XX_utils.feature, src/test/resources/features/tailor_your_return_II/00_about_you.feature
Fixed issue causing beta tailoring tests to fail
=> SASS-10967: Fixed title issue

src/test/resources/features/08_additional_information.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
add remove gains policy scenario to redirect to Your policies page
[SASS-11008](https://jira.tools.tax.service.gov.uk/browse/SASS-11008)
=> SASS-11060 - add remove gains policy scenario

src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-11067 - fix state benefits locators

src/test/resources/features/tailor_your_return_II/01_work_and_taxable_state_benefits.feature, src/test/resources/features/tailor_your_return_II/02_property_pensions_investments.feature, src/test/resources/features/tailor_your_return_II/04_add-sections.feature
=> SASS-11264 - add NINO into session

src/test/resources/features/selfEmployment/SelfEmploymentAccrualAccountingJourney.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-11332: Exclude travel and accommodation journey until it is complete

project/Dependencies.scala
=> [AmendRunner]Reverted ui runner version

build.sbt, project/Dependencies.scala, project/build.properties, src/test/resources/application.conf, src/test/resources/features/08_additional_information.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/AdditionalInfoPage.scala
Adds the Post-Cessation Trade Relief page to the flow.
=> [SASS-11422] Add post-cessation trade relief page to Business Tax Reliefs flow

src/test/resources/features/08_additional_information.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/AdditionalInfoPage.scala
Run against FE branch and passed 🟢
=> [SASS-11420] Adding non-deductible loan interest business tax relief

run_tests.sh, src/test/resources/features/05_cis.feature, src/test/resources/features/07_state_benefits.feature, src/test/scala/uk/gov/hmrc/test/ui/conf/TaxYearHelper.scala, src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonStepDef.scala
=> Changed tax year functionality to fix tests

src/test/resources/features/08_additional_information.feature, src/test/resources/features/property_rar_combined/05_foreign_income.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Add foreign income feature

src/test/resources/features/property_rar_combined/03_uk_and_foreign_property.feature, src/test/resources/features/property_rar_combined/04_foreign_property.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
Updated page titles for SASS-9754 changes.
[SASS-9754](https://jira.tools.tax.service.gov.uk/browse/SASS-9754)
=> SASS-9754 - Foreign property - Change Requests: FP018, FP019 & FP020

src/test/resources/features/selfEmployment/selfEmploymentFeatureSwitch/SelfEmploymentAccrualAccountingJourneyFS.feature, src/test/resources/features/selfEmployment/selfEmploymentFeatureSwitch/SelfEmploymentAccuralUseMaximumTradingAllowanceJourneyFS.feature, src/test/resources/features/selfEmployment/selfEmploymentFeatureSwitch/SelfEmploymentCashAccountJourneyFS.feature
=> Added feature switch feature files for SE

src/test/resources/features/08_additional_information.feature
=> [SASS-11427] add CYA page for post cessation trade relief

src/test/resources/features/08_additional_information.feature
=> SASS-11427 use correct NINO

src/test/resources/features/08_additional_information.feature
FE change:
- https://github.com/hmrc/income-tax-additional-info-frontend/pull/122
=> [SASS-11429] Add CYA page to Non Deductible Loan Interest flow

src/test/resources/features/selfEmployment/selfEmploymentFeatureSwitch/SelfEmploymentAccrualAccountingJourneyFS.feature, src/test/resources/features/selfEmployment/selfEmploymentFeatureSwitch/SelfEmploymentAccuralUseMaximumTradingAllowanceJourneyFS.feature, src/test/resources/features/selfEmployment/selfEmploymentFeatureSwitch/SelfEmploymentCashAccountJourneyFS.feature
=> Added steps to include 'Were you a farmer or market gardener' page

src/test/resources/features/selfEmployment/selfEmploymentFeatureSwitch/SelfEmploymentAccrualAccountingJourneyFS.feature, src/test/resources/features/selfEmployment/selfEmploymentFeatureSwitch/SelfEmploymentAccuralUseMaximumTradingAllowanceJourneyFS.feature, src/test/resources/features/selfEmployment/selfEmploymentFeatureSwitch/SelfEmploymentCashAccountJourneyFS.feature
=> Added steps for 'profit from literary or creative works' page

src/test/resources/features/selfEmployment/SelfEmploymentAccrualAccountingJourney.feature, src/test/resources/features/selfEmployment/SelfEmploymentAccuralUseMaximumTradingAllowanceJourney.feature, src/test/resources/features/selfEmployment/SelfEmploymentCashAccountJourney.feature, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> SASS-11626: Add new industry sectors journey

src/test/resources/features/tailor_your_return_II/15_property_gains.feature, src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/TailoringBetaRunner.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CommonElements.scala
=> Sass 11433

src/test/resources/features/04_employment.feature
=> [SASS-11691] make tax year tests dynamic
